name: StackOverflowUsers
options:
  bundleIdPrefix: com.brunovalente
  deploymentTarget:
    iOS: "16.0"
configs:
  Development: debug
  Production: release
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    TARGETED_DEVICE_FAMILY: "1"
    GCC_TREAT_WARNINGS_AS_ERRORS: YES
    SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
    CLANG_WARN_DOCUMENTATION_COMMENTS: YES
    CLANG_WARN_UNGUARDED_AVAILABILITY: YES_AGGRESSIVE
    GCC_WARN_SHADOW: YES
    GCC_WARN_UNUSED_FUNCTION: YES
targets:
  StackOverflowUsers:
    type: application
    platform: iOS
    sources:
      - path: StackOverflowUsers
    resources:
      - path: StackOverflowUsers/Resources
    configFiles:
      Development: Config/Development.xcconfig
      Production: Config/Production.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_ID_BASE)$(APP_BUNDLE_ID_SUFFIX)
        PRODUCT_NAME: StackOverflowUsers
        INFOPLIST_FILE: StackOverflowUsers/Resources/Info.plist
        GENERATE_INFOPLIST_FILE: NO
  StackOverflowUsersTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: StackOverflowUsersTests
    dependencies:
      - target: StackOverflowUsers
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brunovalente.StackOverflowUsersTests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/StackOverflowUsers.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/StackOverflowUsers"
        BUNDLE_LOADER: "$(TEST_HOST)"
  StackOverflowUsersUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: StackOverflowUsersUITests
    dependencies:
      - target: StackOverflowUsers
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brunovalente.StackOverflowUsersUITests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: StackOverflowUsers
schemes:
  StackOverflowUsers (Development):
    build:
      targets:
        StackOverflowUsers: all
      config: Development
    run:
      config: Development
    test:
      config: Development
      targets:
        - StackOverflowUsersTests
        - StackOverflowUsersUITests
      gatherCoverageData: false
    profile:
      config: Development
    analyze:
      config: Development
    archive:
      config: Development
  StackOverflowUsers (Production):
    build:
      targets:
        StackOverflowUsers: all
      config: Production
    run:
      config: Production
    test:
      config: Production
      targets:
        - StackOverflowUsersTests
        - StackOverflowUsersUITests
      gatherCoverageData: false
    profile:
      config: Production
    analyze:
      config: Production
    archive:
      config: Production
